import { nextRate } from '@/core/settings/settings';

/**
 * Detects clean taps of the bare Shift key, NVDA-style (NAVI-005 spec):
 * - single tap  → play/pause toggle
 * - double tap  → full stop
 *
 * A tap only counts when Shift went down and up again with no other key
 * pressed in between and no other modifier held — so regular typing
 * (Shift+letter) and shortcuts (Ctrl+Shift+…) never trigger it.
 */
export class ShiftTapDetector {
  private cleanTap = false;
  private lastTapAt = Number.NEGATIVE_INFINITY;
  private lastKeyUpAt = Number.NEGATIVE_INFINITY;

  constructor(
    private readonly onSingleTap: () => void,
    private readonly onDoubleTap: () => void,
    private readonly doubleTapWindowMs = 400,
    /**
     * Two keyups closer than this cannot be two human taps — Google Sheets
     * re-dispatches synthetic copies of key events, and counting one physical
     * tap twice turned "pause" into a silent pause+stop.
     */
    private readonly duplicateKeyUpMs = 50,
  ) {}

  handleKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Shift') {
      if (event.repeat) return;
      this.cleanTap = !(event.ctrlKey || event.altKey || event.metaKey);
    } else {
      // Another key while Shift is down → it's a chord, not a tap.
      this.cleanTap = false;
    }
  }

  handleKeyUp(event: KeyboardEvent, now: number = Date.now()): void {
    if (event.key !== 'Shift') return;

    // Duplicate of the same physical release — ignore entirely.
    if (now - this.lastKeyUpAt < this.duplicateKeyUpMs) {
      this.lastKeyUpAt = now;
      return;
    }
    this.lastKeyUpAt = now;

    if (!this.cleanTap) return;
    this.cleanTap = false;

    if (now - this.lastTapAt <= this.doubleTapWindowMs) {
      this.lastTapAt = Number.NEGATIVE_INFINITY;
      this.onDoubleTap();
    } else {
      this.lastTapAt = now;
      this.onSingleTap();
    }
  }
}

export interface SpeechShortcutTarget {
  togglePause(): void;
  stop(): void;
  getRate(): number;
  setRate(rate: number): void;
}

export interface SpeechShortcutOptions {
  /** Called after the rate changes so the caller can persist/announce it. */
  onRateChange?: (rate: number) => void;
  /** Called when the open-NAVI shortcut (Alt/Option+N) is pressed. */
  onOpenNavi?: () => void;
  /**
   * Only react to events generated by real key presses (default true).
   * Google Sheets re-dispatches synthetic keyboard events; reacting to those
   * double-counts every tap. Tests opt out because jsdom cannot create
   * trusted events.
   */
  trustedOnly?: boolean;
}

/**
 * Wires NAVI's keyboard controls onto a document:
 * - Shift (tap)        → pause / resume (replay when idle)
 * - Shift Shift (fast) → stop and clear the queue
 * - Alt + Period (.)   → speak faster
 * - Alt + Comma (,)    → speak slower
 * - Alt + N            → open NAVI (NAVI-001; Option+N on Mac)
 *
 * Returns a detach function.
 */
export function attachSpeechShortcuts(
  doc: Document,
  player: SpeechShortcutTarget,
  options: SpeechShortcutOptions = {},
): () => void {
  const trustedOnly = options.trustedOnly ?? true;

  const detector = new ShiftTapDetector(
    () => player.togglePause(),
    () => player.stop(),
  );

  const onKeyDown = (event: KeyboardEvent) => {
    if (trustedOnly && !event.isTrusted) return;

    // Open NAVI: Alt+N (Option+N on Mac).
    if (
      event.altKey &&
      !event.ctrlKey &&
      !event.metaKey &&
      event.code === 'KeyN'
    ) {
      event.preventDefault();
      event.stopPropagation();
      options.onOpenNavi?.();
      return;
    }

    // Rate keys: Alt+. / Alt+, (chosen to avoid Google Sheets + NVDA combos).
    if (
      event.altKey &&
      !event.ctrlKey &&
      !event.metaKey &&
      (event.code === 'Period' || event.code === 'Comma')
    ) {
      event.preventDefault();
      event.stopPropagation();
      const direction = event.code === 'Period' ? 1 : -1;
      const rate = nextRate(player.getRate(), direction);
      player.setRate(rate);
      options.onRateChange?.(rate);
      return;
    }

    detector.handleKeyDown(event);
  };

  const onKeyUp = (event: KeyboardEvent) => {
    if (trustedOnly && !event.isTrusted) return;
    detector.handleKeyUp(event);
  };

  doc.addEventListener('keydown', onKeyDown, true);
  doc.addEventListener('keyup', onKeyUp, true);

  return () => {
    doc.removeEventListener('keydown', onKeyDown, true);
    doc.removeEventListener('keyup', onKeyUp, true);
  };
}
